import { createHash, randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { env } from "@/lib/env";

export type StoredFile = {
  key: string;
  contentType: string;
  size: number;
};

/**
 * Files are written to a local volume today. Everything goes through this
 * interface so an S3 driver can replace it without touching call sites.
 */
export interface StorageAdapter {
  put(body: Buffer, contentType: string, extension: string): Promise<StoredFile>;
  get(key: string): Promise<{ body: Buffer; contentType: string } | null>;
  delete(key: string): Promise<void>;
  url(key: string): string;
}

const ALLOWED = new Map<string, string>([
  ["image/svg+xml", "svg"],
  ["image/png", "png"],
  ["image/jpeg", "jpg"],
  ["image/webp", "webp"],
  ["application/pdf", "pdf"],
]);

export const MAX_UPLOAD_BYTES = 4 * 1024 * 1024;

export function extensionForType(contentType: string): string | null {
  return ALLOWED.get(contentType) ?? null;
}

/**
 * An uploaded SVG is markup that we later inline on the guest's phone and on
 * the live screen, so scripts, event handlers and external references have to
 * come out before it is stored.
 */
export function sanitiseSvg(svg: string): string {
  return svg
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/<foreignObject[\s\S]*?<\/foreignObject>/gi, "")
    .replace(/\son\w+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi, "")
    .replace(/(href|xlink:href)\s*=\s*("|')\s*(javascript|data):[^"']*\2/gi, "")
    .replace(/<!ENTITY[\s\S]*?>/gi, "");
}

class LocalStorage implements StorageAdapter {
  private readonly root: string;

  constructor(root: string) {
    this.root = path.resolve(root);
  }

  private async ensureRoot() {
    if (!existsSync(this.root)) await mkdir(this.root, { recursive: true });
  }

  // Content-addressed, so re-uploading the same logo doesn't duplicate it and
  // the served URL can be cached forever.
  private static keyFor(body: Buffer, extension: string) {
    const digest = createHash("sha256").update(body).digest("hex").slice(0, 32);
    return `${digest}.${extension}`;
  }

  private pathFor(key: string) {
    // Keys are generated by us, but never trust one that came back through a
    // request: resolve and check it stayed inside the root.
    const resolved = path.resolve(this.root, key);
    if (!resolved.startsWith(this.root + path.sep)) {
      throw new Error("Refusing to resolve a storage key outside the uploads root");
    }
    return resolved;
  }

  async put(body: Buffer, contentType: string, extension: string): Promise<StoredFile> {
    await this.ensureRoot();
    const key = LocalStorage.keyFor(body, extension);
    await writeFile(this.pathFor(key), body);
    await writeFile(`${this.pathFor(key)}.type`, contentType, "utf8");
    return { key, contentType, size: body.byteLength };
  }

  async get(key: string) {
    const file = this.pathFor(key);
    if (!existsSync(file)) return null;
    const body = await readFile(file);
    const contentType = existsSync(`${file}.type`)
      ? await readFile(`${file}.type`, "utf8")
      : "application/octet-stream";
    return { body, contentType: contentType.trim() };
  }

  async delete(key: string) {
    const file = this.pathFor(key);
    if (existsSync(file)) await unlink(file);
    if (existsSync(`${file}.type`)) await unlink(`${file}.type`);
  }

  url(key: string) {
    return `/api/files/${key}`;
  }
}

export const storage: StorageAdapter = new LocalStorage(env.UPLOADS_DIR);

/** Validates, sanitises and stores one uploaded file. */
export async function storeUpload(file: File): Promise<StoredFile> {
  const extension = extensionForType(file.type);
  if (!extension) {
    throw new UploadError(`Unsupported file type: ${file.type || "unknown"}`);
  }
  if (file.size > MAX_UPLOAD_BYTES) {
    throw new UploadError("File is larger than 4 MB");
  }

  let body = Buffer.from(await file.arrayBuffer());
  if (extension === "svg") {
    body = Buffer.from(sanitiseSvg(body.toString("utf8")), "utf8");
  }

  return storage.put(body, file.type, extension);
}

export class UploadError extends Error {}

/** Used where a key is needed before the bytes exist (generated posters). */
export function scratchKey(extension: string) {
  return `${randomUUID()}.${extension}`;
}
